version: 2.1
jobs:
  firmware-build:
    docker:
      - image: kktech/firmware:v14
    working_directory: ~/keepkey-firmware
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            git submodule update --init --recursive
      - setup_remote_docker
      - run:
          name: Build Emulator and Run Tests
          command: |
            mkdir /root/build && cd /root/build
            cmake -C /root/keepkey-firmware/cmake/caches/device.cmake /root/keepkey-firmware \
              -DCMAKE_BUILD_TYPE=MinSizeRel \
              -DCMAKE_COLOR_MAKEFILE=ON
            make
            mkdir -p /root/keepkey-firmware/bin
            cp -r /root/build /root/keepkey-firmware/bin/
            cp bin/*.bin /root/keepkey-firmware/bin/
            cp bin/*.elf /root/keepkey-firmware/bin/
            chown -R `stat -c "%u:%g" /root/keepkey-firmware` /root/keepkey-firmware/bin
      - store_artifacts:
          path: ./bin/firmware.keepkey.bin
          destination: Release/firmware.keepkey.bin

  emulator-build-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            git submodule update --init --recursive
      - setup_remote_docker
      - run:
          name: Build Emulator and Run Tests
          command: |
            pushd ./scripts/emulator
            set +e
            docker-compose up --build firmware-unit
            docker-compose up --build python-keepkey
            set -e
            mkdir -p ../../test-reports
            docker cp "$(docker-compose ps -q firmware-unit)":/kkemu/test-reports/. ../../test-reports/
            docker cp "$(docker-compose ps -q python-keepkey)":/kkemu/test-reports/. ../../test-reports/
            popd
            [ "$(cat test-reports/python-keepkey/status)$(cat test-reports/firmware-unit/status)" == "00" ] || exit 1
      - store_test_results:
          path: test-reports

  emulator-publish:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: |
            git submodule update --init --recursive
      - setup_remote_docker
      - run:
          name: Build Emulator
          command: |
            pushd ./scripts/emulator
            docker-compose build kkemu
            popd
      - run:
          name: Publish Emulator
          command: |
            docker login -u $KK_DOCKERHUB_USER -p $KK_DOCKERHUB_PASS
            docker push kktech/kkemu
            LATEST_IMAGE_ID=$(docker images | grep -i kktech/kkemu | grep -i latest | awk '{print $3}' )
            FW_VERSION=$(cat ./CMakeLists.txt | tr -d '\n' | awk -v FS="(KeepKeyFirmwareVERSION|LANGUAGES)" '{print $1}' | awk '{print $4}')
            docker tag $LATEST_IMAGE_ID kktech/kkemu:v$FW_VERSION
            docker push kktech/kkemu

workflows:
  version: 2
  firmware:
    jobs:
      - firmware-build
